FROM tomcat:alpine

# We do not want to keep the default applications, remove them
#
RUN rm -rf /usr/local/tomcat/webapps/*
#
# Demo Server
COPY net.loginbuddy.demoserver/target/demoserver-1.0.0 /usr/local/tomcat/webapps/ROOT

COPY docker-build/add-ons/demoserver/loginbuddy.sh /opt/docker/loginbuddy.sh
COPY docker-build/add-ons/demoserver/permissions.policy /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
COPY docker-build/add-ons/demoserver/server.xml /usr/local/tomcat/conf/server.xml
COPY docker-build/add-ons/templates/hazelcastPermissions.policy /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hazelcastPermissions.policy

# Create directory for holding SSL keys
#
RUN mkdir /usr/local/tomcat/ssl

ENV HOSTNAME_LOGINBUDDY_DEMOSERVER demoserver.loginbuddy.net

ENTRYPOINT ["/opt/docker/loginbuddy.sh"]