FROM tomcat:alpine

# We do not want to keep the default applications, remove them
#
RUN rm -rf /usr/local/tomcat/webapps/*

# add our own application as the one and only
#
# Default loginbuddy services
COPY net.loginbuddy.service/target/service-1.0.0 /usr/local/tomcat/webapps/ROOT
#
# Demo Server
COPY net.loginbuddy.demoserver/target/demoserver-1.0.0 /usr/local/tomcat/webapps/demoserver
#
# Demo Client
COPY net.loginbuddy.democlient/target/democlient-1.0.0 /usr/local/tomcat/webapps/democlient

COPY docker-build/add-ons/demosetup/web.xml /usr/local/tomcat/conf/web.xml
COPY docker-build/add-ons/demosetup/loginbuddy.sh /opt/docker/loginbuddy.sh
COPY docker-build/add-ons/demosetup/server.xml /usr/local/tomcat/conf/server.xml
COPY docker-build/add-ons/demosetup/catalina.policy /usr/local/tomcat/conf/catalina.policy
COPY docker-build/add-ons/demosetup/config.json /usr/local/tomcat/webapps/ROOT/config/config.json

# create non-priviliged user (with its own group) to run tomcat
#
RUN addgroup tomcat
RUN adduser -SG tomcat tomcat
RUN chown -R tomcat:tomcat /usr/local/tomcat/

ENTRYPOINT ["/opt/docker/loginbuddy.sh"]