FROM tomcat:alpine

# We do not want to keep the default applications, remove them
#
RUN rm -rf /usr/local/tomcat/webapps/*
#
# Demo Client
COPY net.loginbuddy.democlient/target/democlient-1.0.0 /usr/local/tomcat/webapps/ROOT

# Create directory for holding SSL keys
#
RUN mkdir /usr/local/tomcat/ssl

ENV HOSTNAME_LOGINBUDDY_DEMOSERVER demoserver.loginbuddy.net

ENTRYPOINT ["/opt/docker/loginbuddy.sh"]