FROM saschazegerman/loginbuddy:latest
#
# Demo Server
COPY net.loginbuddy.demoserver/target/demoserver-1.0.0 /usr/local/tomcat/webapps/demoserver
#
# Demo Client
COPY net.loginbuddy.democlient/target/democlient-1.0.0 /usr/local/tomcat/webapps/democlient

COPY docker-build/add-ons/demosetup/config.json /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
COPY docker-build/add-ons/demosetup/discovery.json /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
COPY docker-build/add-ons/demosetup/loginbuddy.sh /opt/docker/loginbuddy.sh
COPY docker-build/add-ons/demosetup/permissions.policy /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
COPY docker-build/add-ons/demosetup/server.xml /usr/local/tomcat/conf/server.xml
COPY docker-build/add-ons/demosetup/server_loginbuddy.png /usr/local/tomcat/webapps/ROOT/images/server_loginbuddy.png
COPY docker-build/add-ons/server/loginbuddy_selfissued_import.sh /opt/docker/loginbuddy_selfissued_import.sh

ENV HOSTNAME_LOGINBUDDY local.loginbuddy.net
ENV HOSTNAME_LOGINBUDDY_DEMOCLIENT democlient.loginbuddy.net

ENTRYPOINT ["/opt/docker/loginbuddy.sh"]