#
# This docker compose file is usable for development purposes:
#
# NOTE: use this only for local development purposes!
#
# IMPORTANT:
# loginbuddy-sidecar and loginbuddy-oidcdr should NOT expose ports in an 'online' scenario! Port 444 and 445 are available to other
# containers within the same docker network by default! Do NOT include a port mapping! Here it is done for testing purposes only!
#
version: '3.4'
services:

  loginbuddy-oidcdr:
    image: saschazegerman/loginbuddy-oidcdr:latest
    restart: always
    ports:
      - "445:445"
      - "8002:8002"
      - "9012:9012"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8002,suspend=n,server=y"

  loginbuddy-demo:
    image: saschazegerman/loginbuddy-demo:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "9010:9010"
    volumes:
      - ./config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
      - ./discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
      - ./permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
      - ./loginbuddy.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/loginbuddy.properties
      - ./testCustomLoginbuddyConfig.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/testCustomLoginbuddyConfig.json
      - ./configTemplates.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/configTemplates.json
      - ./test-classes/net/loginbuddy/config/loginbuddy/CustomLoginbuddyConfigLoader.class:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/net/loginbuddy/config/loginbuddy/CustomLoginbuddyConfigLoader.class
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8000,suspend=n,server=y"
      - "SUPPORT_OIDCDR=true"

  loginbuddy-test:
    image: saschazegerman/loginbuddy-test:latest
    restart: always
    ports:
      - "8003:8003"
      - "8999:8080"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8003,suspend=n,server=y"